version: '3.1'

services:

    wordpress:
        image: wordpress
        restart: always
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: exampleuser
            WORDPRESS_DB_PASSWORD: examplepass
            WORDPRESS_DB_NAME: exampledb
        volumes:
            - ./wordpress_data:/var/www/html

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: exampledb
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepass
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - ./mysql_data:/var/lib/mysql

    myadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8081:80" # Access phpMyAdmin at http://localhost:8081/ with user root and password mysql
        environment:
            PMA_HOST: "db"
            UPLOAD_LIMIT: 1073741824 # Limit 1GB
        # networks:
        #     - mysql

# volumes:
#   wordpress: ''
#   db: ''